### PR TITLE
Update for 2020

### PR DESCRIPTION
**Pull request by themikesmith**
Pending final validation from library staff

### CODE REVIEW

**Comment by themikesmith** [comment]
Hi there, I'm writing my own dissertation now, and have updated your template for 2020 guidelines. I've begun uploads on CTAN and Overleaf too.

**Comment by skulumani** [comment]
Thanks @themikesmith much appreciated. I'll review it soon. 

Can you upload the packages to CTAN/Overleaf? I thought it had some kind of permission system or can anyone just update the package?

**Comment by themikesmith** [comment]
Thanks very much!

FYI: 
- I resolved some formatting issues, played around with package requirements and import order, among other things, and defined some new variables for ease of user manipulation in `tex/frontmatter.tex` based on what I found myself needing to edit. 
- Hopefully I did everything right as it's been a bit since I've worked in LaTeX; the only warnings remaining are "underfull/overfull hbox" related to the content in `tex/manual.tex`, judging by my Overleaf project: https://www.overleaf.com/read/skfcphfsfssr 

> Can you upload the packages to CTAN/Overleaf? I thought it had some kind of permission system or can anyone just update the package?

I have no idea whether either of the CTAN or Overleaf uploads will succeed, but I've submitted to be reviewed for both. I think CTAN will (if it succeeds) handle versioning properly, but Overleaf is TBD - it might create a new template. I've asked Overleaf if templates require re-submission or do they automatically pick up changes in the referential template project --- do you happen to know the answer?

**Comment by skulumani** [comment]
I think the best approach is to wait for final approval from the library on the changes, then commit a final version here, then make sure the CTAN and Overleaf version match.

**Comment by themikesmith** [comment]
Sounds good regarding approval.
FYI, from Overleaf:
Thanks for getting in touch! You can update the same original project and
click "Submit" > "Overleaf Gallery" again. This will update the template in
the Gallery, after it's been approved.

**Comment by skulumani** [comment]
Also I'm assuming you're already in contact with the ETD office at the library? And that they're reviewing your updated thesis template?

**Comment by themikesmith** [comment]
Correct, yep! Should hear soon. I'll have a few more tweaks to commit I
imagine... Was it this nitpicky when you were writing yours?

**Comment by skulumani** [comment]
>  Was it this nitpicky when you were writing yours?

It took me over a year to get it finally approved. Not sure why they feel the need to change it. I'm assuming it's a new person at ETD who is just following their own prerogative.

**Comment by themikesmith** [comment]
Hi there, I received what I believe should be the last feedback from the gw
library.
I have one question for you: I had to use the tocloft package to indent the
table of contents, but this disregarded (I think) some of the formatting
you had done in the class file. This starts on current line 906. What's the
best way to know what was overridden and what wasn't? We can comment or
remove what is unnecessary to avoid future confusion
Best,
Mike

**Comment by skulumani** [comment]
Thanks! @themikesmith 

> I have one question for you: I had to use the tocloft package to indent the
table of contents, but this disregarded (I think) some of the formatting
you had done in the class file.

I'm sure this is fine and probably a better way to do it than what I originally did in the class file. I'll have to review it to remember how I had it setup. I'll try to look at your changes this weekend.

> Hi there, I received what I believe should be the last feedback from the gw
library.

Can you add a screenshot/PDF of whatever "approved" message you have from the library? That was we can include it when someone new shows up and tries to change things. 

Could you also ask why this is being changed in the first place from 2018? The reason for a standard/template is consistency.

**Comment by themikesmith** [comment]
No problem!
Another question: do you wish to continue maintaining this? I can take over
if you want, but I can't promise all the fancy services like Travis and
others at the top of your Readme. Rest of replies inline
Best
Michael




On Wed, Mar 4, 2020, 1:18 PM Shankar Kulumani <notifications@github.com>
wrote:

> Thanks! @themikesmith <https://github.com/themikesmith>
>
> I have one question for you: I had to use the tocloft package to indent the
> table of contents, but this disregarded (I think) some of the formatting
> you had done in the class file.
>
> I'm sure this is fine and probably a better way to do it than what I
> originally did in the class file. I'll have to review it to remember how I
> had it setup. I'll try to look at your changes this weekend.
>
Please do. I felt very hacky!

> Hi there, I received what I believe should be the last feedback from the gw
> library.
>
> Can you add a screenshot/PDF of whatever "approved" message you have from
> the library? That was we can include it when someone new shows up and tries
> to change things.
>
Perhaps, yes, but it's an email chain. I'm not sure how I can finagle Gmail
to display what I want. I can try soon

> Could you also ask why this is being changed in the first place from 2018?
> The reason for a standard/template is consistency.
>
That, I unfortunately don't know; likely above my pay grade. It looks like
it changed in 2019 across the university. Maybe this change is the
beginning of consistency?

**Comment by skulumani** [comment]
I'm getting the following errors:

~~~
thesis-sample.tex|277 warning| Underfull \hbox (badness 2409) in paragraph at lines 277--279
thesis-sample.tex|280 warning| Underfull \hbox (badness 1616) in paragraph at lines 280--283
thesis-sample.tex|298 warning| Overfull \hbox (4.56004pt too wide) in paragraph at lines 298--306
thesis-sample.tex|289 warning| Overfull \hbox (17.48888pt too wide) in paragraph at lines 289--309
thesis-sample.tex|312 warning| LaTeX Warning: Citation `newton1999' on page 10 undefined on input line 312.
thesis-sample.tex|315 warning| LaTeX Warning: Citation `kalman1960' on page 10 undefined on input line 315.
thesis-sample.tex|315 warning| LaTeX Warning: Citation `shannon1949' on page 10 undefined on input line 315.
./thesis-sample.bbl|1 error| Use of \reserved@a doesn't match its definition.
./thesis-sample.bbl|1 error| Argument of \ttl@assign@i has an extra }.
./thesis-sample.bbl|1 error| Paragraph ended before \ttl@assign@i was complete.
./thesis-sample.bbl|1 error| Argument of \ttl@assign@i has an extra }.
./thesis-sample.bbl|1 error| Paragraph ended before \ttl@assign@i was complete.
./thesis-sample.bbl|1 error| Extra }, or forgotten \endgroup.
thesis-sample.tex|| LaTeX Warning: There were undefined references.
thesis-sample.tex|| LaTeX Warning: Label(s) may have changed. Rerun to get cross-references right.
~~~

Can you figure out what's going on?

**Comment by themikesmith** [comment]
Hi Shankar, unfortunately I'm getting no errors. In addition, I am only
getting three warnings at this point (I resolved a couple of the others you
mentioned) -- but all of the warnings are from the manual chapter that was
created before my contributions to the repo. See below.
Could you try clearing your cache and intermediate build files and
recompiling? Alternatively, did a code merge fail on your end? See attached
for a zip of the project, too, in case that helps you reset.
Best,
Mike
[image: image.png]

**Comment by skulumani** [comment]
No worries. Let me check on it

**Comment by skulumani** [comment]
> Another question: do you wish to continue maintaining this? I can take over
if you want, but I can't promise all the fancy services like Travis and
others at the top of your Readme. Rest of replies inline

I can add you as a contributor to this repo? That way all the other stuff should just keep working? And then the repo can still be used as the source for the template? 

I'll try to double check the thesis tonight. It might be a latex issue on my end. I tried installing texlive from the ubuntu repo instead of directly from texlive itself.

**Comment by themikesmith** [comment]
On Mon, Mar 9, 2020 at 8:45 AM Shankar Kulumani <notifications@github.com>
wrote:

> Another question: do you wish to continue maintaining this? I can take over
> if you want, but I can't promise all the fancy services like Travis and
> others at the top of your Readme. Rest of replies inline
>
> I can add you as a contributor to this repo? That way all the other stuff
> should just keep working? And then the repo can still be used as the source
> for the template?
>
Sure if you like! Thanks

> I'll try to double check the thesis tonight. It might be a latex issue on
> my end. I tried installing texlive from the ubuntu repo instead of directly
> from texlive itself.
>
Sounds good. Let me know if I can assist.

**Comment by skulumani** [comment]
Thanks for the help. Just merged and pushed to  CTAN. 

Hope it's good!

**Comment by themikesmith** [comment]
HI Shankar, sounds good! How did you resolve the issues?
Merged and pushed to CTAN - excellent!
What's outstanding:

   - Overleaf? I will handle this by updating the template
   - Are you still open to me contributing officially to the repo?
   - Do you want me to update the README indicating 2020 compatibility?

Best
Mike

**Comment by themikesmith** [comment]
I didn't see access to your repo, so I've just updated the README in mine
and made another pull request.

Looking forward to hearing from you on the admin status and rest of the
README

Stay healthy,
Mike

**Comment by skulumani** [comment]
Sorry! I just invited you as a collaborator. Let me know if it works

**Pull request merged**
